"""empty message

Revision ID: 6ba22dff8bf9
Revises: edf4c3c2bf49
Create Date: 2023-04-22 18:17:36.423599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba22dff8bf9'
down_revision = 'edf4c3c2bf49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
