"""empty message

Revision ID: edf4c3c2bf49
Revises: 6ffad669f449
Create Date: 2023-04-22 18:08:16.652878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf4c3c2bf49'
down_revision = '6ffad669f449'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
